In [1]:
import os
import torch
import matplotlib.pyplot as plt
import numpy as np
import re
from scipy.stats import spearmanr
import csv

import warnings
warnings.filterwarnings("ignore")
import _logix

In [ ]:
grad = torch.load("grad.pt", weights_only=False)
grad_cov = torch.load("cov_grad.pt", weights_only=False)
grad_cov_inv = torch.load("cov_inverse.pt", weights_only=False)


my_grad = torch.load("my_grad.pt", weights_only=False)
my_grad_cov = torch.load("my_grad_covariance.pt", weights_only=False)
my_cov_inverse = torch.load("my_cov_inverse.pt", weights_only=False)

In [7]:
print(grad['lm_head.logix_lora_B']['grad'])

tensor([[ 0.0051, -0.0026,  0.0014,  ...,  0.0011,  0.0007,  0.0015],
        [-0.0014,  0.0007, -0.0008,  ..., -0.0047,  0.0018, -0.0048],
        [ 0.0098, -0.0038,  0.0033,  ...,  0.0006,  0.0005,  0.0007],
        [-0.0046,  0.0013, -0.0015,  ..., -0.0086,  0.0020, -0.0070]],
       device='cuda:0')


In [8]:
print(my_grad['lm_head'][0])

tensor([[ 0.0051, -0.0026,  0.0014,  ...,  0.0011,  0.0007,  0.0015],
        [-0.0014,  0.0007, -0.0008,  ..., -0.0047,  0.0018, -0.0048],
        [ 0.0098, -0.0038,  0.0033,  ...,  0.0006,  0.0005,  0.0007],
        [-0.0046,  0.0013, -0.0015,  ..., -0.0086,  0.0020, -0.0070]])


In [5]:
print(my_grad_cov['lm_head']['grad'])

tensor([[ 6.8121e-06, -2.1162e-06,  2.6578e-06,  ...,  2.0718e-06,
         -7.6377e-07,  1.5839e-06],
        [-2.1162e-06,  7.7293e-07, -7.4684e-07,  ..., -3.9882e-07,
          1.2720e-07, -2.1467e-07],
        [ 2.6578e-06, -7.4684e-07,  1.1908e-06,  ...,  1.1133e-06,
         -4.1519e-07,  8.8285e-07],
        ...,
        [ 2.0718e-06, -3.9882e-07,  1.1133e-06,  ...,  1.9989e-06,
         -7.9683e-07,  1.8093e-06],
        [-7.6377e-07,  1.2720e-07, -4.1519e-07,  ..., -7.9683e-07,
          4.3374e-07, -8.1526e-07],
        [ 1.5839e-06, -2.1467e-07,  8.8285e-07,  ...,  1.8093e-06,
         -8.1526e-07,  1.7788e-06]])


In [6]:
print(grad_cov['lm_head.logix_lora_B']['grad'])

tensor([[ 6.8120e-06, -2.1162e-06,  2.6577e-06,  ...,  2.0718e-06,
         -7.6377e-07,  1.5839e-06],
        [-2.1162e-06,  7.7293e-07, -7.4684e-07,  ..., -3.9882e-07,
          1.2720e-07, -2.1467e-07],
        [ 2.6577e-06, -7.4684e-07,  1.1908e-06,  ...,  1.1133e-06,
         -4.1519e-07,  8.8285e-07],
        ...,
        [ 2.0718e-06, -3.9882e-07,  1.1133e-06,  ...,  1.9989e-06,
         -7.9683e-07,  1.8093e-06],
        [-7.6377e-07,  1.2720e-07, -4.1519e-07,  ..., -7.9683e-07,
          4.3374e-07, -8.1526e-07],
        [ 1.5839e-06, -2.1467e-07,  8.8285e-07,  ...,  1.8093e-06,
         -8.1526e-07,  1.7788e-06]], device='cuda:0')
