In [10]:
import torch
import torch.nn as nn
import os

import warnings
warnings.filterwarnings("ignore")

from tqdm import tqdm
import numpy as np

from scipy.stats import spearmanr
import csv

In [2]:
def read_nodes(file_path):
    int_list = []
    with open(file_path, 'r') as csvfile:
        csv_reader = csv.reader(csvfile)
        for row in csv_reader:
            for item in row:
                try:
                    int_list.append(int(item))
                except ValueError:
                    print(f"Warning: '{item}' could not be converted to an integer and was skipped.")
    return int_list

def calculate_one(path):
    # score = torch.load(path, map_location=torch.device('cpu'))  # _test_0225_regroup
    score = torch.load(path, map_location=torch.device('cpu'))
    # score = torch.rand(5000, 500)
    print("score shape:", score.shape)

    nodes_str = []
    for i in range(50):
        nodes_str.append(f"./checkpoints/{i}/train_index.csv")

    full_nodes = [i for i in range(4656)]

    node_list = []
    for node_str in nodes_str:
        numbers = read_nodes(node_str)
        index = []
        for number in numbers:
            index.append(full_nodes.index(number))
        node_list.append(index)

    loss_list = torch.load("./result/gt.pt", map_location=torch.device('cpu')).detach()

    approx_output = []
    for i in range(len(nodes_str)):
        score_approx_0 = score[node_list[i], :]
        sum_0 = torch.sum(score_approx_0, axis=0)
        approx_output.append(sum_0)

    print(len(loss_list), loss_list[0].shape)
    print(len(approx_output), approx_output[0].shape)

    res = 0
    counter = 0
    for i in range(score.shape[1]):
        tmp = spearmanr(np.array([approx_output[k][i] for k in range(len(approx_output))]),
                        np.array([loss_list[k][i].numpy() for k in range(len(loss_list))])).statistic
        if np.isnan(tmp):
            print("Numerical issue")
            continue
        res += tmp
        counter += 1

    print(counter)

    return res/counter, loss_list, approx_output


In [14]:
path = "./result/score.pt"
print(calculate_one(path)[0])

score shape: torch.Size([4, 1])


IndexError: index 3155 is out of bounds for dimension 0 with size 4

In [15]:
score = torch.load('./result/score_GIP.pt', map_location=torch.device('cpu'))
# score = torch.rand(5000, 500)
print("score shape:", score.shape)
print(score)

score shape: torch.Size([4, 1])
tensor([[0.0619],
        [0.0660],
        [0.0732],
        [0.0473]])


In [16]:
score = torch.load('./result/score.pt', map_location=torch.device('cpu'))
# score = torch.rand(5000, 500)
print("score shape:", score.shape)
print(score)

score shape: torch.Size([4, 1])
tensor([[0.0314],
        [0.0454],
        [0.0459],
        [0.0352]])


In [8]:
x = np.array([0.0656, 0.0806, 0.0821, 0.708])

x * (0.0338 / 0.0656)

array([0.0338    , 0.04152866, 0.04230152, 0.36479268])